# Generated by Django 2.2.6 on 2020-02-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', help_text='First name', max_length=32)),
                ('last_name', models.CharField(default='', help_text='Last name', max_length=32)),
                ('email', models.EmailField(default='', help_text='Enter a valid email address', max_length=64)),
                ('number', models.CharField(default='', help_text='Mobile Phone Number', max_length=10)),
                ('profile_pic', models.ImageField(default='', max_length=500, null=True, upload_to='media/profile_pics')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
