# Generated by Django 2.2.6 on 2019-12-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(blank=True, help_text='The Riders that manage the community. Designated by the owner.', related_name='moderator_of_rideshare_community', to='rideshare.Rider'),
        ),
    ]
