# Generated by Django 2.2.6 on 2020-03-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='areas',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
