# Generated by Django 2.2.6 on 2019-12-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_auto_20191210_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(help_text='A description of your rideshare community', null=True),
        ),
    ]
