# Generated by Django 2.2.6 on 2019-12-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideshare',
            name='return_date',
            field=models.DateField(blank=True, help_text='OPTIONAL: When the driver plans to return from end location (if is offering return trip)'),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='return_trip',
            field=models.BooleanField(blank=True, help_text='If the driver is taking passengers on the ride back'),
        ),
    ]
