# Generated by Django 2.2.6 on 2019-12-11 01:56

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_auto_20191211_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='areas',
            field=models.ManyToManyField(blank=True, help_text='The areas in which this community will offer rideshares in (this is used for Riders to find the right communities)', to='rideshare.Location'),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='end_location',
            field=models.ForeignKey(help_text='The end location of this rideshare', on_delete=django.db.models.deletion.CASCADE, related_name='endlocation_of_rideshare_rideshare', to='rideshare.Location'),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='start_location',
            field=models.ForeignKey(help_text='The start location of this rideshare', on_delete=django.db.models.deletion.CASCADE, related_name='startlocation_of_rideshare_rideshare', to='rideshare.Location'),
        ),
    ]
