# Generated by Django 2.2.6 on 2019-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_auto_20191212_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideshare',
            name='return_trip',
            field=models.BooleanField(blank=True, help_text='If the driver is taking passengers on the ride back', null=True),
        ),
    ]
