# Generated by Django 2.2.6 on 2019-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_auto_20191213_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideshare',
            name='passengers',
            field=models.ManyToManyField(blank=True, help_text='The passengers who will be embarking on this trip', null=True, related_name='passenger_of_rideshare_rideshare', to='rideshare.Rider'),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='pending_passengers',
            field=models.ManyToManyField(blank=True, help_text='The passengers who whish to embark on this trip but have not been accepted by the driver yet', null=True, related_name='pendingpassenger_of_rideshare_rideshare', to='rideshare.Rider'),
        ),
        migrations.AlterField(
            model_name='rideshare',
            name='return_date',
            field=models.DateField(blank=True, help_text='OPTIONAL: When the driver plans to return from end location (if is offering return trip)', null=True),
        ),
    ]
