# Generated by Django 2.2.7 on 2020-02-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0009_auto_20191213_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
