# Generated by Django 2.2.6 on 2020-02-25 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0009_auto_20191213_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='rideshare.Community')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
