# Generated by Django 2.2.6 on 2020-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0010_auto_20200225_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RideTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='rideshare',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='rideshare',
            name='start_location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
