# Generated by Django 2.2.7 on 2020-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_auto_20200217_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='blacklist_users',
            field=models.CharField(blank=True, help_text='Users in blacklist', max_length=10000),
        ),
    ]
