# Generated by Django 2.2.7 on 2020-02-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0013_community_blacklist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='private',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
