# Generated by Django 2.2.7 on 2020-02-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_community_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_requests',
            field=models.ManyToManyField(blank=True, help_text='Requests from riders to join a community', related_name='request_members_of_rideshare_community', to='rideshare.Rider'),
        ),
    ]
