# Generated by Django 2.2.7 on 2020-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0015_community_member_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshare',
            name='rating',
            field=models.IntegerField(blank=True, help_text='community rating integer', null=True),
        ),
        migrations.AddField(
            model_name='rideshare',
            name='review',
            field=models.TextField(blank=True, help_text='drivers and riders can share reviews of the trip', null=True),
        ),
    ]
