# Generated by Django 2.2.7 on 2020-02-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0016_auto_20200219_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideshare',
            name='rating',
        ),
        migrations.AddField(
            model_name='rideshare',
            name='rating',
            field=models.ManyToManyField(blank=True, help_text='community rating integer', null=True, related_name='rating_of_rideshare_rideshare', to='rideshare.Rider'),
        ),
        migrations.RemoveField(
            model_name='rideshare',
            name='review',
        ),
        migrations.AddField(
            model_name='rideshare',
            name='review',
            field=models.ManyToManyField(blank=True, help_text='drivers and riders can share reviews of the trip', null=True, related_name='review_of_rideshare_rideshare', to='rideshare.Rider'),
        ),
    ]
