# Generated by Django 2.2.7 on 2020-02-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0017_auto_20200219_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideshare',
            old_name='rating',
            new_name='reviewer',
        ),
    ]
