# Generated by Django 2.2.7 on 2020-02-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0018_auto_20200219_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideshare',
            name='review',
        ),
        migrations.RemoveField(
            model_name='rideshare',
            name='reviewer',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.ManyToManyField(blank=True, help_text='drivers and riders can share reviews of the trip', null=True, related_name='review_of_rideshare_review', to='rideshare.Rider')),
                ('reviewer', models.ManyToManyField(blank=True, help_text='community rating integer', null=True, related_name='rating_of_rideshare_review', to='rideshare.Rider')),
            ],
        ),
    ]
