# Generated by Django 2.2.7 on 2020-02-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0019_auto_20200219_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshare',
            name='reviews',
            field=models.ManyToManyField(blank=True, help_text='review object from rider', null=True, related_name='review_of_rideshare_rideshare', to='rideshare.Review'),
        ),
    ]
