# Generated by Django 2.2.7 on 2020-02-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0020_rideshare_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, help_text='user review string', null=True),
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='The Rider who is offering to drive the trip', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_of_rideshare_review', to='rideshare.Rider'),
        ),
    ]
